# dataset path



H_coors: True
# model
model: model.intra_stage.Model 
model_args:
  in_channels: 1792
  n_target: 1   
  k_nearest: 5 
  k_threshold: 0.1
  hiddens: [128,128,128] 
  dropout: 0.3 
  drop_max_ratio: 0.05

#optim
weight_decay: 0.0005 
base_lr: 0.01 
lr_decay_rate: 0.1
step: 150
num_epoch: 200

# training
device: [0]
batch_size: 16
test_batch_size: 16

