work_dir: work_dir/intra_stage/tcga_luad/
loss: loss.coxph_loss
n_fold: 5
data_seed: 1
dataset: dataset.WSI_Dataset.SlidePatch
center: ['TCGA-LUAD']
WSI_info_list_file: dataset/WSI_info_list/TCGA-LUAD.json
WSI_patch_ft_dir: get_feature/WSI_patch_features/{}_2K_sample_threshold/patch_ft
WSI_patch_coor_dir: get_feature/WSI_patch_features/{}_2K_sample_threshold/patch_coor

H_coors: True
# model
model: model.intra_stage.Model 
model_args:
  in_channels: 512 
  n_target: 1   
  k_nearest: 5 
  k_threshold: 0.1
  hiddens: [128,128,128] 
  dropout: 0.3 
  drop_max_ratio: 0.05

#optim
weight_decay: 0.0005 
base_lr: 0.01 
lr_decay_rate: 0.1
step: 150
num_epoch: 200

# training
device: [0]
batch_size: 16
test_batch_size: 16
